-- ============================================================
-- 퀴즈 스키마 정리 (데일리 퀴즈 본체)
-- 날짜: 2026-04-17
-- 변경사항:
--   1. quizzes 데이터 전량 삭제 + 의존 테이블 정리
--   2. course_categories 마스터 테이블 신설
--   3. quizzes 컬럼 정리: source, category, correct_rate 삭제
--   4. quiz_code: TEXT('Q00001') → INT IDENTITY (1, 2, 3...)
--   5. course_category TEXT → course_category_id FK
-- ============================================================

BEGIN;

-- ========== 0. 데이터 정리 ==========
DELETE FROM user_quiz_scraps;
DELETE FROM wrong_notes WHERE quiz_id IS NOT NULL;
UPDATE attendance_records SET quiz_id = NULL WHERE quiz_id IS NOT NULL;
DELETE FROM quiz_answers;
DELETE FROM quizzes;

-- ========== 1. course_categories 마스터 ==========
CREATE TABLE IF NOT EXISTS course_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO course_categories (name, display_order) VALUES
  ('예적금', 1),
  ('연금', 2),
  ('주식', 3),
  ('부동산', 4),
  ('세금', 5),
  ('소비', 6)
ON CONFLICT (name) DO NOTHING;

-- ========== 2. 불필요 컬럼 삭제 ==========
ALTER TABLE quizzes DROP COLUMN IF EXISTS source;
ALTER TABLE quizzes DROP COLUMN IF EXISTS category;
ALTER TABLE quizzes DROP COLUMN IF EXISTS correct_rate;

-- ========== 3. quiz_code: TEXT → INT IDENTITY ==========
ALTER TABLE quizzes ALTER COLUMN quiz_code DROP DEFAULT;
ALTER TABLE quizzes DROP COLUMN IF EXISTS quiz_code;
DROP SEQUENCE IF EXISTS quiz_code_seq;

ALTER TABLE quizzes
  ADD COLUMN quiz_code INT GENERATED BY DEFAULT AS IDENTITY UNIQUE;

-- ========== 4. course_category TEXT → FK ==========
DROP INDEX IF EXISTS idx_quizzes_course_category;
ALTER TABLE quizzes DROP COLUMN IF EXISTS course_category;
ALTER TABLE quizzes ADD COLUMN course_category_id UUID
  REFERENCES course_categories(id);
CREATE INDEX idx_quizzes_course_category_id ON quizzes(course_category_id);

-- ========== 5. updated_at ==========
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

COMMIT;
